development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 5
        connect_timeout: 10
        socket_timeout: 10
        server_selection_timeout: 10

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_TEST_URI'] || 'mongodb://localhost:27017/cityhive_test' %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 20
        connect_timeout: 30
        socket_timeout: 30
        server_selection_timeout: 30
        max_retries: 1
        retry_writes: true
        heartbeat_frequency: 10
